### ISSUE TITLE
Needs to update icon set from original repo

### ISSUE THREAD

**Issue by vdanchenkov** [abdelhai/react-bytesize-icons#1]
specifically from this commit https://github.com/danklammer/bytesize-icons/commit/f67c69a42dd21b98038d3ab34c38e802e0c76574

Is this library code autogenerated? If not, I could update it manually.

**Comment by abdelhai** [comment]
@vdanchenkov thanks for letting me know.
It's not autogenerated but it's super easy to update manually. I will merge asap if you would send me a PR.

**Comment by Kilian** [comment]
I could also very much use an update of the npm package! @abdelhai Are you planning on still maintaining this?

**Comment by abdelhai** [comment]
@Kilian I'm not maintaining it at the moment. You are welcome to contribute or fork.

**Comment by Kilian** [comment]
@abdelhai That's alright, I'll update it. Would you still accept pull requests and update NPM, or would you mind handing over access for that to me?

@vdanchenkov I'll try and see if I can write an automated script :)

**Comment by abdelhai** [comment]
Thanks @Kilian 🙌  I've added you as a collaborator.

**Comment by Kilian** [comment]
I've released a new version 0.8.0 that adds the missing icons!
